[package]
name = "synapse_project"
version = "0.1.0"
edition = "2021"
authors = ["Xzdes <your@email.com>"]
description = "Synapse ASG/SYN1 prototype"
license = "MIT"

[dependencies]
anyhow = "1.0"
byteorder = "1.5"
varint = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Основной бинарник
[[bin]]
name = "synapse_project"
path = "src/main.rs"

# Бинарник-генератор пустого .synapse файла
[[bin]]
name = "generate_empty_synapse"
path = "src/tools/generate_empty_synapse.rs"

[[bin]]
name = "generate_literal_add"
path = "src/tools/generate_literal_add.rs"