[package]
name = "synapse"
version = "0.1.0"
edition = "2021"
authors = ["Xzdes <your@email.com>"]
description = "Experimental Synapse programming language (ASG, SYN1, interpreter, generators)"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.5"
varint = "0.9"
bit_utils = "0.1"

[lib]
name = "synapse"
path = "src/lib.rs"

[[bin]]
name = "synapse"
path = "src/main.rs"

[[bin]]
name = "generate_add_print"
path = "src/tools/generate_add_print.rs"

[[bin]]
name = "generate_conditional"
path = "src/tools/generate_conditional.rs"

[[bin]]
name = "generate_empty_synapse"
path = "src/tools/generate_empty_synapse.rs"

[[bin]]
name = "generate_gt_if"
path = "src/tools/generate_gt_if.rs"

[[bin]]
name = "generate_literal_add"
path = "src/tools/generate_literal_add.rs"

[[bin]]
name = "generate_float_sub"
path = "src/tools/generate_float_sub.rs"

[[bin]]
name = "convert_synapse_json"
path = "src/tools/convert_synapse_json.rs"
